# Site Settings
title: "JavaScript Room | Web Development Consulting"
email: "info@roomjs.com"
description: "JavaScript Room - your best advisor in the IT world!"
baseurl: /
ogimage: "/img/jsroom-og.png"
url: "https://roomjs.com" # the base hostname & protocol for your site

# Google Analytics ID
gauid: "G-VN0VLRSRZ2"

# Build settings
markdown: kramdown

# Plugins
# plugins:
#   - jemoji
