# Site Settings
title: "JavaScript Room | Web Development | Consulting | Blog"
email: "info@roomjs.com"
description: "Use the best modern technologies to build digital worlds of the future"
baseurl: /
ogimage: "/img/jsroom-og.png"
url: "https://roomjs.com" # the base hostname & protocol for your site

# Google Analytics ID
gauid: "G-VN0VLRSRZ2"

# Build settings
markdown: kramdown

# Plugins
# plugins:
#   - jemoji
